### ISSUE TITLE
Add Contributing guide

### ISSUE THREAD

**Issue by chrisdukakis** [iotaledger/iota.js#291]
### Description
Repo lacks a `CONTRIBUTING.md`, let's add it.

### Motivation
Explain a standard workflow we use in iota.js monorepo to help everyone contributing.

### Requirements
- [ ] Add a Code of Conduct and link to it.
- [ ] Describe a lifecycle for issues & pull requests.
- [ ] Fork/clone/installation guide (copy from readme).
- [ ] Explain lerna workflow (mostly done in readme).
- [ ] Explain testing setup (local & CI).
- [ ] Documentation guide.
- [ ] Conventional commits/PRs guide to explain precommit hooks & conventional commits (see also: https://github.com/iotaledger/iota.js/issues/292).
- [ ] Update README.md with shorter section and link to Contributing guide.

### Am I planning to do it myself with a PR?
Yes

**Comment by laumair** [comment]
Contribution guide added with https://github.com/iotaledger/iota.js/commit/e758ff420afd7be233013d803d1e3d6404461269.
