### ISSUE TITLE
Enable conventional commits, changelog & semantic releases 

### ISSUE THREAD

**Issue by chrisdukakis** [iotaledger/iota.js#292]
### Description
This issue tracks addition of conventional changelog and automated releases.

### Requirements
- [x] Enforce conventional commit messages with a tool like [`commitizen`](https://github.com/commitizen/cz-cli) and/or [`commitlint`](https://github.com/marionebl/commitlint). (#294)
- [x] Configure `lerna/publish` to bump and generate changelog based on conventional commits. (#294)
- [x] Check if new PRs have semantic title/commit message (https://github.com/apps/semantic-pull-requests or http://marionebl.github.io/commitlint/#/guides-ci-setup). (#310)
- [ ] Add CI automation to publish upon merges to stable branch.

### Motivation
Automation, reduced maintenance cost and improved contributing experience. Also conventional changelogs offer a transparent and full overview of what has been worked on, and are comprehensible to wider audience.

### Am I planning to do it myself with a PR?
Yes

**Comment by obany** [comment]
Closing as this relates to an unmaintained branch of the library, which will be incompatible with the new Chrysalis release of the network.
